name: Deploy
run-name: Realizando deploy 🚀🚀🚀

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    
    steps:
      - name: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.PRODUCTION_DEPLOY_KEY }}"
