name: Deploy
run-name: Realizando deploy 🚀🚀🚀

on:
  workflow_run:
    workflows: [Testes]
    types:
      - completed

# on:
#   workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    # needs: [build, test]
    if: github.ref_name == 'main'
    steps:
      - name: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.render.com/deploy/${{ secrets.PRODUCTION_DEPLOY_KEY }}&ref=${{ github.sha }}"


#   deploy-staging:
#     runs-on: ubuntu-latest
#     # needs: [build, test]
#     if: github.ref_name == 'main'
#     steps:
#       - name: deploy
#         uses: fjogeleit/http-request-action@v1
#         with:
#           url: "https://api.render.com/deploy/${{ secrets.STAGING_DEPLOY_KEY }}&ref=${{ github.sha }}"



















          #   deployment:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#       - name: Deploy Stage
#         uses: fjogeleit/http-request-action@v1
#         with:
#           url: "https://ansible.io/api/v2/job_templates/84/launch/"
#           method: "POST"
#           username: ${{ secrets.AWX_USER }}
#           password: ${{ secrets.AWX_PASSWORD }}
#           customHeaders: '{"Content-Type": "application/json"}'
#           data: '{"key_1": "value_1", "key_2": "value_2"}'
