name: Deploy
run-name: Realizando deploy 🚀🚀🚀

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Carregando variáveis de ambiente
        uses: actions-ecosystem/action-dotenv@v2
        with:
          dotenv_path: .env

      - name: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "$PRODUCTION"
